spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pay?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: Lay163228,
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9090